from typing import Any

BUILTIN_PLUGINS: list[dict[str, Any]] = [
    {
        "id": "core-text-tools",
        "name": "课堂文字工具",
        "description": "内置文字生成、润色、解释和编程助手能力。",
        "category": "ai_tool",
        "version": "0.1.0",
        "entry": "builtin://text",
        "capabilities": ["text", "code_explain"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "core-image-tools",
        "name": "课堂图片工具",
        "description": "内置文生图、图片作品保存和本地预览能力。",
        "category": "ai_tool",
        "version": "0.1.0",
        "entry": "builtin://image",
        "capabilities": ["image"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "workflow-template-pack",
        "name": "少儿课堂工作流模板包",
        "description": "内置文字生成图片、创意扩写、代码解释和项目规划模板。",
        "category": "workflow",
        "version": "0.1.0",
        "entry": "builtin://workflow-templates",
        "capabilities": ["workflow"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "local-model-adapter",
        "name": "本地模型适配器",
        "description": "预留本地模型接入位，后续可接入 Ollama、LM Studio 或私有推理服务。",
        "category": "adapter",
        "version": "0.1.0",
        "entry": "adapter://local-model",
        "capabilities": ["text", "local_model"],
        "enabled": False,
        "builtin": True,
        "status": "planned",
    },
    {
        "id": "video-generation-adapter",
        "name": "视频生成适配器",
        "description": "预留文生视频和图生视频运行适配器，首版先完成配置识别。",
        "category": "adapter",
        "version": "0.1.0",
        "entry": "adapter://video-generation",
        "capabilities": ["video"],
        "enabled": False,
        "builtin": True,
        "status": "planned",
    },
]
