from typing import Any

BUILTIN_PLUGINS: list[dict[str, Any]] = [
    {
        "id": "core-text-tools",
        "name": "课堂文字工具",
        "description": "内置文字生成、润色、解释和提示词优化能力。",
        "category": "ai_tool",
        "version": "0.1.0",
        "entry": "builtin://text",
        "capabilities": ["text", "prompt_refine"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "core-image-tools",
        "name": "课堂图片工具",
        "description": "内置文生图、图片作品保存和本地预览能力。",
        "category": "ai_tool",
        "version": "0.1.0",
        "entry": "builtin://image",
        "capabilities": ["image"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "workflow-template-pack",
        "name": "少儿课堂工作流模板包",
        "description": "内置文字生成图片、创意扩写、代码解释和项目规划模板。",
        "category": "workflow",
        "version": "0.1.0",
        "entry": "builtin://workflow-templates",
        "capabilities": ["workflow"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "local-model-adapter",
        "name": "本地模型适配器",
        "description": "通过 OpenAI 兼容接口连接 API 服务器可访问的 Ollama、LM Studio 或机构私有推理服务。",
        "category": "adapter",
        "version": "1.0.0",
        "entry": "adapter://local-openai-compatible",
        "capabilities": ["text", "local_model"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
    {
        "id": "video-generation-adapter",
        "name": "MiniMax 视频生成适配器",
        "description": "支持 MiniMax 文生视频、图生视频、任务查询、失败重试和结果保存。",
        "category": "adapter",
        "version": "1.0.0",
        "entry": "adapter://minimax-video",
        "capabilities": ["video"],
        "enabled": True,
        "builtin": True,
        "status": "ready",
    },
]
